apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  selector:
    app: node-app #
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31200